{
    "openapi": "3.0.0",
    "info": {
        "title": "Ayapone Backend APIs",
        "description": "Powering the next generation cryptocurrency e-Commerce platform.",
        "version": "1.0",
        "x-logo": {
            "url": "https://github.com/Ayagigs/Ayapone-Backend/blob/main/assets/imgs/ayapone.png?raw=true",
            "backgroundColor": "#FFFFFF",
            "altText": "AYAPONE"
        },
        "contact": {
            "url": "https://ayapone-backend.onrender.com/api/v1"
        },
        "license": {
            "name": "GNU GENERAL PUBLIC LICENSE",
            "url": "https://github.com/Ayagigs/Ayapone-Backend/blob/main/LICENSE"
        }
    },
    "servers": [
        {
            "url": "http://{{baseurl}}"
        }
    ],
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Auth"
        },
        {
            "name": "User Management"
        },
        {
            "name": "Products"
        },
        {
            "name": "Products > Brands"
        },
        {
            "name": "Products > Categories"
        },
        {
            "name": "Products > Products"
        },
        {
            "name": "Products > Review"
        },
        {
            "name": "Checkout"
        },
        {
            "name": "Cart"
        }
    ],
    "paths": {
        "/auth/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "email": "saitama_punch@yopmail.com",
                                    "password": "123456",
                                    "remember_me": true
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Merchant - Sign up",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "last_name": "Hyuga",
                                    "first_name": "Hinata",
                                    "email": "kudakuda@yopmail.com",
                                    "phone_number": "+2348909090909",
                                    "password": "123456",
                                    "id_type": "voters_card",
                                    "id_number": "1234ert432r455E4T5DR654dr",
                                    "id_front_image_url": "",
                                    "id_back_image_url": "",
                                    "businessKyc": {
                                        "business_name": "Kabin",
                                        "registration_number": "RC6767",
                                        "business_type": "others",
                                        "address": "",
                                        "city": "",
                                        "state": "",
                                        "country": "",
                                        "postal_code": "",
                                        "usdt_address": "0x3f5CE5FBFe3E9af3971dD833D26bA9b5C936f0bE",
                                        "usdt_address_type": "BEP20"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Verify Email",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "email": "saitama_punch@yopmail.com",
                                    "token": 936122
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/auth/request-password-reset": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Request Password Reset",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "email": "saitama_punch@yopmail.com"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Set New Password",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "token": "J8cLD6ExhTsBZg46FDtlo0juwv89LGORD12f51GbetkW5RasZ",
                                    "new_password": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/auth/regenerate-token": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Regenerate Access Token",
                "requestBody": {
                    "content": {}
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "tags": [
                    "User Management"
                ],
                "summary": "Fetch All Users",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/user/{userId}": {
            "get": {
                "tags": [
                    "User Management"
                ],
                "summary": "Fetch User By Id",
                "parameters": [
                    {
                        "name": "userId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/user": {
            "patch": {
                "tags": [
                    "User Management"
                ],
                "summary": "Update User",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "last_name": "Punch",
                                    "first_name": "Saitama",
                                    "username": "one_punch_man",
                                    "phone_number": "+2348909090909",
                                    "id_type": "voters_card",
                                    "id_number": "489094890090909",
                                    "id_front_image_url": "",
                                    "id_back_image_url": ""
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/user/change-password": {
            "patch": {
                "tags": [
                    "User Management"
                ],
                "summary": "Change Password",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "old_password": "1234567",
                                    "new_password": "123456"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/user/upload-profile-photo": {
            "post": {
                "tags": [
                    "User Management"
                ],
                "summary": "Change Profile Photo",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "files": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/user/upload-cover-photo": {
            "post": {
                "tags": [
                    "User Management"
                ],
                "summary": "Change Cover Photo",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "files": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/user/add-admin": {
            "post": {
                "tags": [
                    "User Management"
                ],
                "summary": "Create An Admin",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "last_name": "Yolla",
                                    "first_name": "Minn",
                                    "email": "yolla@yopmail.com",
                                    "phone_number": "+23456567888766",
                                    "password": "123456"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/user/close-account": {
            "delete": {
                "tags": [
                    "User Management"
                ],
                "summary": "Delete My Account",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/brands": {
            "post": {
                "tags": [
                    "Products > Brands"
                ],
                "summary": "create brand",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Nikel"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Products > Brands"
                ],
                "summary": "get brands",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/brands/640ca8f10a02249707c63866": {
            "patch": {
                "tags": [
                    "Products > Brands"
                ],
                "summary": "update",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Addidas"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/brands/64059a933f01936d8ca45adf": {
            "delete": {
                "tags": [
                    "Products > Brands"
                ],
                "summary": "delete brand",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/category": {
            "post": {
                "tags": [
                    "Products > Categories"
                ],
                "summary": "create",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Belts"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Products > Categories"
                ],
                "summary": "get",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/category/6405a35a2678c1c86207b1cb": {
            "patch": {
                "tags": [
                    "Products > Categories"
                ],
                "summary": "update",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Belts"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Products > Categories"
                ],
                "summary": "delete",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/products": {
            "post": {
                "tags": [
                    "Products > Products"
                ],
                "summary": "create",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Laces",
                                    "description": "Nike shoe laces",
                                    "delivery": 2,
                                    "price": 200,
                                    "brandId": "640ca8f10a02249707c63866",
                                    "categoryId": "640ca9a27d90c3fe6ed5c072"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Products > Products"
                ],
                "summary": "get all",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/products/64075cf5b3993408d9de5710": {
            "delete": {
                "tags": [
                    "Products > Products"
                ],
                "summary": "delete",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/products/user": {
            "get": {
                "tags": [
                    "Products > Products"
                ],
                "summary": "get all by user",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/products/640761cd33eed876d8e66b56": {
            "patch": {
                "tags": [
                    "Products > Products"
                ],
                "summary": "update",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Laced "
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/reviews": {
            "post": {
                "tags": [
                    "Products > Review"
                ],
                "summary": "Create Review",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "orderId": "640ca9f41b63bde88eb28530",
                                    "productId": "640ca9f41b63bde88eb28530",
                                    "comment": "looks good",
                                    "rating": "3.5"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Products > Review"
                ],
                "summary": "Fetch Reviews by Current User",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/reviews/product/{productId}": {
            "get": {
                "tags": [
                    "Products > Review"
                ],
                "summary": "Fetch Reviews for a Product",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "productId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/reviews/{reviewId}": {
            "get": {
                "tags": [
                    "Products > Review"
                ],
                "summary": "Fetch Review by ID",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "reviewId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Products > Review"
                ],
                "summary": "Update Review",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "comment": "looks good",
                                    "rating": "1.5"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "reviewId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Products > Review"
                ],
                "summary": "Delete Review",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "reviewId",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/checkout": {
            "post": {
                "tags": [
                    "Checkout"
                ],
                "summary": "checkout",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "last_name": "Habiku",
                                    "first_name": "Kanga",
                                    "email": "kanga@yopmail.com",
                                    "phone_number": "+2349809898776",
                                    "addrress_one": "house way, bloodline street",
                                    "addrress_two": "",
                                    "city": "Tampo",
                                    "state": "Jagi",
                                    "country": "Layth",
                                    "postal_code": "23423"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/checkout/delivery-info": {
            "get": {
                "tags": [
                    "Checkout"
                ],
                "summary": "Get Delivery Info",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/cart": {
            "post": {
                "tags": [
                    "Cart"
                ],
                "summary": "add to cart",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "productId": "640ce6cd673eabc57d136d75",
                                    "quantity": 1
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Cart"
                ],
                "summary": "Get Cart",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Cart"
                ],
                "summary": "remove product from cart",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "productId": "640ca9f41b63bde88eb28530"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/cart/clear": {
            "post": {
                "tags": [
                    "Cart"
                ],
                "summary": "empty cart",
                "requestBody": {
                    "content": {}
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        }
    }
}